[workspace]

resolver="2"

members = [
    "mining-proxy",
    "pool",
    "test-utils/mining-device",
    "test-utils/sv1-mining-device",
    "translator",
    "jd-client",
    "jd-server",
    "tests-integration",
]

[profile.dev]
# Required by super_safe_lock
opt-level = 1

[profile.test]
# Required by super_safe_lock
opt-level = 1
