[package]
name = "buffer_sv2"
version = "1.1.0"
authors = ["The Stratum V2 Developers"]
edition = "2018"
description = "buffer"
documentation = "https://docs.rs/buffer_sv2"
readme = "README.md"
homepage = "https://stratumprotocol.org"
repository = "https://github.com/stratum-mining/stratum"
license = "MIT OR Apache-2.0"
keywords = ["stratum", "mining", "bitcoin", "protocol"]

[dependencies]
criterion = {version = "0.3", optional = true}
serde = { version = "1.0.89", features = ["derive", "alloc"], default-features = false, optional = true }
aes-gcm = "0.10.2"

[dev-dependencies]
rand = "0.8.3"
iai = "0.1"


[[bench]]
name = "pool_benchmark"
harness = false

[[bench]]
name = "pool_iai"
harness = false

[features]
debug = []
fuzz = []
with_serde = ["serde"]

[package.metadata.docs.rs]
all-features = true