on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Clippy Lint

jobs:
  clippy-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
          components: clippy
      - name: Run Clippy on different workspaces and crates
        run: |
          cargo clippy --manifest-path=benches/Cargo.toml -- -D warnings -A dead-code
          cargo clippy --manifest-path=common/Cargo.toml -- -D warnings -A dead-code
          cargo clippy --manifest-path=protocols/Cargo.toml -- -D warnings -A dead-code
          cargo clippy --manifest-path=roles/Cargo.toml -- -D warnings -A dead-code
          cargo clippy --manifest-path=utils/Cargo.toml -- -D warnings -A dead-code
          cargo clippy --manifest-path=utils/message-generator/Cargo.toml -- -D warnings -A dead-code
